### ISSUE TITLE
How to activate coverage workflow?

### ISSUE THREAD

**Issue by christophsax** [blockr-org/blockr.extra#1]
No urgency, but if you could give me a tip on how to activate the coverage workflow for this package, @DivadNojnarg? I copied your `.yml` content from blockr.

https://github.com/blockr-org/blockr.extra/actions/runs/7653017673/job/20854079729

**Comment by DivadNojnarg** [comment]
@christophsax. This workflow requires a `CODECOV_TOKEN`:

```yaml
env:
      CODECOV_TOKEN: ${{ secrets.CODECOV_TOKEN }}
```

I just added it from codecov.

**Comment by christophsax** [comment]
Thanks!
